import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  popupContainer: {
    width: 314.5,
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    paddingVertical: 33,
    paddingHorizontal: 32,
    alignItems: 'center',
  },
  popupImage: {
    width: 88.22,
    height: 70.75,
    marginBottom: 24,
  },
  textContainer: {
    alignItems: 'center',
    marginBottom: 27,
  },
  subTitle: {
    fontFamily: 'Pretendard',
    fontWeight: '700',
    fontSize: 14,
    color: '#000000',
    marginBottom: 8,
  },
  highlightText: {
    color: '#1BC5CC',
  },
  mainTitle: {
    fontFamily: 'Pretendard',
    fontWeight: '700',
    fontSize: 20,
    color: '#000000',
  },
  courseBox: {
    width: 250.5,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 28,
    alignItems: 'center',
    marginBottom: 12,
  },
  courseLabel: {
    fontFamily: 'Pretendard',
    fontWeight: '400',
    fontSize: 9,
    color: '#8A8A8A',
    marginBottom: 8,
  },
  coursePath: {
    fontFamily: 'Pretendard',
    fontWeight: '500',
    fontSize: 14,
    lineHeight: 20,
    color: '#8A8A8A',
    textAlign: 'center',
  },
  buttonContainer: {
    width: 250.5,
    gap: 12,
  },
  startButton: {
    height: 44,
    backgroundColor: '#FFB826',
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 2,
    marginBottom: 12,
  },
  startButtonText: {
    fontFamily: 'Pretendard',
    fontWeight: '700',
    fontSize: 16,
    color: '#FFFFFF',
  },
  backButton: {
    height: 44,
    backgroundColor: '#E0E0E0',
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  backButtonText: {
    fontFamily: 'Pretendard',
    fontWeight: '700',
    fontSize: 16,
    color: '#8A8A8A',
  },
});